### ISSUE TITLE
Option for removing single or multiple empty lines

### ISSUE THREAD

**Issue by BMasquio** [shufo/blade-formatter#10]
Add an option for removing the unnecessary lines.

### Example input:
```
<div>




    <div>
        Hello World!
    </div>
</div>
```

### Example output:
```
<div>
    <div>
        Hello World!
    </div>
</div>
```

**Comment by shufo** [comment]
@BMasquio 
Thanks for the feature suggestion!

This could be done with other tools like sed.
e.g. 
```bash
find resources/**/*.blade.php | xargs sed -i '/^$/d'
```

I'd think it's not bad to implement this behaivour but blade-formatter's purpose is to format blade syntax and other tool's task is not in the scope.
sed is more better to do this task than blade-formatter so please consider to use sed to remove blank line.
