### ISSUE TITLE
[Question]Do you have plans for stdin support?

### ISSUE THREAD

**Issue by yaegassy** [shufo/blade-formatter#110]
Thanks for this tool.

I mainly use `Vim`.

Support for `stdin` makes it easier and more convenient to integrate from other editors.

**Example:**

```
cat sample.blade.php | blade-formatter
# or
cat sample.blade.php | blade-formatter -
```

Do you have a plan for `stdin` support?

**Comment by shufo** [comment]
@yaegassy 
Currently there is no road map for stdin but I think it's good idea to support stdin.

```bash
cat sample.blade.php | blade-formatter -
```
or ESLint like option might good for compatibility

```bash
Using stdin:
  --stdin                         Lint code provided on <STDIN> - default: false
```

I would like to add stdin support in next or next next minor version update.

Thanks for feature suggestion!

**Comment by yaegassy** [comment]
@shufo Thanks reply!

I'm looking forward to adding more features in the future.
This issue is closed.

**Comment by shufo** [comment]
Released v1.7.0 with stdin support.
https://github.com/shufo/blade-formatter/releases/tag/v1.7.0

**Comment by yaegassy** [comment]
Congratulations on your release!
I've confirmed that it works fine in my environment.

**Comment by mzaini30** [comment]
@yaegassy How to auto run this stdin after save in Vim? I new in Vim
