### ISSUE TITLE
@if in html class occurs error

### ISSUE THREAD

**Issue by ikeane** [shufo/blade-formatter#129]
## Expected Behavior
```blade
@if (count($topics))
  <ul class="list-group border-0">
    @foreach ($topics as $topic)
      <li class="list-group-item border-right-0 border-left-0 @if($loop->first) border-top-0 @endif"></li>
    @endforeach
  </ul>
@endif
```

## Current Behavior
```blade
@if (count($topics))
  <ul class="list-group border-0">
    @foreach ($topics as $topic)
      <li class="list-group-item border-right-0 border-left-0 <beautify start=" @if " exp=" ^^^$loop->first^^^">
        border-top-0
    @endif"></li>
@endforeach
</ul>
@endif
```

**Comment by shufo** [comment]
It seems inline directive causes error.

To work around this, you can convert inline condition to non-inline condition.

```blade
@if (count($topics))
  <ul class="list-group border-0">
    @foreach ($topics as $topic)
      @if($loop->first)
        <li class="list-group-item border-right-0 border-left-0"></li>
      @else
        <li class="list-group-item border-right-0"></li>
      @endif
    @endforeach
  </ul>
@endif
```

Please try it on https://online-blade-formatter.vercel.app/

**Comment by vielhuber** [comment]
Any update on this? This is crucial, as it destroys code.

**Comment by shufo** [comment]
Just released https://github.com/shufo/blade-formatter/releases/tag/v1.9.8 with this bug fixed

**Comment by vielhuber** [comment]
Very good! It works now.
Do you consider the vs-code extension as stable? It's not working at all.
I'm using currently a RunOnSave approach (which works stable), but as a extension this would be even more awesone.

**Comment by shufo** [comment]
@vielhuber 
Thank you for using extension!
I would say that [VSCode extension](https://github.com/shufo/vscode-blade-formatter) is stable in most cases.
However, it may become unstable when the open/close of HTML tags and the open/close of blade directive are mixed.

I've also seen some issues that it conflicts with other Blade extensions. It is recommended to use it with Syntax highlighter like https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade.

If it still not working, i would appreciate if you report your environment to issues.
