### ISSUE TITLE
Buffer() DeprecationWarning on VS Code v1.49

### ISSUE THREAD

**Issue by netway-pairote** [shufo/blade-formatter#141]
The issue occurs only the first time enable blade-formatter, after that it works just fine.

## Steps to Reproduce
1. On VS Code v1.49,  install the extension.
2. Set user config (~/.config/Code/User/settings.json)
```
  "editor.formatOnSave": true,
  "[blade]": {
    "editor.autoClosingBrackets": "always",
    "editor.defaultFormatter": "shufo.vscode-blade-formatter"
  },
```
3. Open any blade.php file, make a change and save. It will show warning notification, and waiting for something.

> Saving 'xxxxxx.blade.php': Running 'Laravel Blade formatter' Formatter ([configure](command:workbench.action.openSettings...

4. Click 'cancel', on the  warning notification to stop it. I found the following warning on VS Code output panel, BLADE Language Server channel.

> [Error - 8:18:13 AM] (node:7037) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Noted that if I make change on the blade file again, it will works as expected.

**Comment by shufo** [comment]
@netway-pairote 
Thanks for reporting issue! I'll try reproducing it.
