### ISSUE TITLE
What does complicated mean in the error message

### ISSUE THREAD

**Issue by SudoGetBeer** [shufo/blade-formatter#205]
Hey,

first of all this look like a really cool tool. Thanks for that.

So I tried it with a few blade files. But I this error for some files:
"Please check if template is too complicated or not. Or simplify template might solves issue."

What does too complicated mean? Too much lines or too much capsuled blocks?

**Comment by shufo** [comment]
@SudoGetBeer 

Thank you!

For example, currently it can not handle blade directive inside script block.

```blade
<script>
@if ($condition)
	let a = 1;
@else
	let a = 2;
@end
</script>
```

or sometimes it can not handle html and blade nested each other like 

```js
<div>
@if ($condition)
  <div>
@else
  </div>
@end
</div>
```

Too avoid this issue, unnest each language blocks or separate conditional block might solves this error.

```blade
@if ($condition)
  <div>
    foo
  </div>
@else
  <div>
    bar
  </div>
@end
```
