### ISSUE TITLE
Object operator inside @if directives breaks aligned attributes

### ISSUE THREAD

**Issue by kyori19** [shufo/blade-formatter#211]
## Expected Behavior
```blade.php
<input class="@if (empty($object->property)) something @endif"
       value="test" />
```

## Current Behavior
```blade.php
<input class="@if (empty($object->property)) something @endif"
value="test" />
```

## Possible Solution
Probably `>` inside `@if` directives regarded as xml tag closing symbol.
Any codes inside `@if` directives should be regarded as PHP.

## Steps to Reproduce
Format html inside Expected Behavior using blade-formatter with `--wrap-attributes preserve-aligned`.

## Context (Environment)
via VSCode extension v0.7.0

**Comment by shufo** [comment]
Perhaps this issue has been fixed in the current latest version https://github.com/shufo/blade-formatter/releases/tag/v1.21.4 along with fixing other issues. 
Thank you @kyori19!

Latest behaviour 

```blade
<input class="@if (empty($object->property)) something @endif" value="test" id="foo" />
```

will format into

```blade
❯ ./bin/blade-formatter test22.blade.php --wrap 80
<input class="@if (empty($object->property)) something @endif" value="test"
    id="foo" />
```
