### ISSUE TITLE
array_reduce function breaks

### ISSUE THREAD

**Issue by formikaio** [shufo/blade-formatter#222]
## Current Behavior
These lines:
@php
    $n = array_reduce($c, function ($tot, $i) {return $tot + $i; }, 0);
@endphp 

are formatted like this:
@php
$n = array_reduce(
    $c,
    function ($tot, $i) {
        return $tot + $i;
    },
    0,
);
@endphp

An extra comma is added after the last parameter (probably the formatter mistakes the array_reduce function for an array declaration). The issue probably affects other array_* functions.

**Comment by shufo** [comment]
@formikaio 
Thank you for reporting issue.
blade-formatter currently formats php strings as php `7.4` and php version above 7.3 supprots [trailing commas in functions](https://laravel-news.com/php-trailing-commas-functions).



![image](https://user-images.githubusercontent.com/1641039/111906987-b2894480-8a96-11eb-8364-6ec989c97ef0.png)

![image](https://user-images.githubusercontent.com/1641039/111906974-a4d3bf00-8a96-11eb-8fce-5b1d2c98c813.png)

If your environment is below 7.3, it does not support trailing comma syntax and it might happen syntax exception.

I think the possible solution is to allow users to select the php version for format style.
I'm not sure if this is a good solution, but I'll take consider it.
