### ISSUE TITLE
formatter white space inside directive arrow in a blade file

### ISSUE THREAD

**Issue by med-rezzouq** [shufo/blade-formatter#231]
## Expected Behavior
  <script>
@isset($data['eval_gestionnaire']->project_perception)
@endisset
</script>

## Current Behavior
  <script>
 @isset($data['eval_gestionnaire'] - > project_perception)
@endisset
</script>

## Possible Solution
Except using @json() to declare the object outside isset , is there any other solution?  -->

**Comment by med-rezzouq** [comment]
I think that the Formatter used to add spaces around > or < operators when at comparation and also add spaces around - when doing caculations but in that cases we have -> directive which needs to be excluded is that the issue if so i will be glad to add this as an exception and skip adding spaces to them, thank you in advance

**Comment by shufo** [comment]
seems related to #208

**Comment by med-rezzouq** [comment]
no , isn't the case i can write blade code inside script tag, the issue is only with the space arround the -> , i wish you can edit the formatter to don't add spaces around id, my issue is so clear, thanks any way ...

**Comment by shufo** [comment]
Fixed this behaviour on https://github.com/shufo/blade-formatter/releases/tag/v1.10.7
