### ISSUE TITLE
PHP code inside Blade @if and @foreach produce incorrect code

### ISSUE THREAD

**Issue by wb-joona** [shufo/blade-formatter#304]
Hey, thanks for putting this project out. It's great to see someone making an effort towards autoformatting Blade templates!

## Expected Behavior

I would expect the formatter to not modify the code's semantics.

## Current Behavior

When formatting a document with PHP code inside a Blade `@if` or `@foreach` block, the formatter produces incorrect output, and repeated formats mutate the code further until ending up in a broken state.

## Steps to Reproduce

1. Format the following code with blade-formatter 1.11.9:
```
<div>
    @if ($foobars)
        <?php
        // This is a comment
        echo 'foobar';
        ?>
    @endif
</div>
```
2. Observe that the output is:

```
<div>
    @if ($foobars)
        <?php // This is a comment
        echo 'foobar'; ?>
    @endif
</div>
```

3. Format it again, and observe that the comment is duplicated and an additional `?>` is inserted, breaking the code:
```
<div>
    @if ($foobars)
        <?php // This is a comment
        // This is a comment
        ?>echo 'foobar'; ?>
    @endif
</div>
```

4. Format it yet again, and observe that the code is now:
```
<div>
    @if ($foobars)
        <?php
        // This is a comment
        // This is a comment
        ?>echo 'foobar'; ?>
    @endif
</div>
```

5. Further formats do not produce any further changes.

Here's a gif showing me repeatedly formatting the code:
![0uWoFGr0jy](https://user-images.githubusercontent.com/85222502/124753013-2c9fe500-df31-11eb-8d0b-3c671993ec96.gif)

**Comment by shufo** [comment]
Hi @wb-joona.
This behaviour is fixed in https://github.com/shufo/blade-formatter/releases/tag/v1.11.10.
