### ISSUE TITLE
@section('scripts')  ...   @append obvious indent bug

### ISSUE THREAD

**Issue by rsdsoft** [shufo/blade-formatter#313]
```
@section('scripts')
    @append
```
obvious indent bug

**Comment by shufo** [comment]
@rsdsoft 
It seems valid syntax in that part.
Can you tell me full body of template? Thanks.

**Comment by rsdsoft** [comment]
Do you see wrong indent for @append in my message? But should behave like @endsection (without any indents relative to @section). This behaviour in any template.

**Comment by shufo** [comment]
Thank you @rsdsoft
This behavior seemed to be caused by `@append` directive was not supported in blade-formatter.
Released https://github.com/shufo/blade-formatter/releases/tag/v1.11.12 with this behaviour fixed.

**Comment by rsdsoft** [comment]
Thanks for the VSCode extension

**Comment by rsdsoft** [comment]
> Thank you @rsdsoft
> This behavior seemed to be caused by `@append` directive was not supported in blade-formatter.
> Released https://github.com/shufo/blade-formatter/releases/tag/v1.11.12 with this behaviour fixed.

The same issue with @overwrite btw.
