### ISSUE TITLE
@overwrite indent

### ISSUE THREAD

**Issue by rsdsoft** [shufo/blade-formatter#327]
> Thank you @rsdsoft
> This behavior seemed to be caused by `@append` directive was not supported in blade-formatter.
> Released https://github.com/shufo/blade-formatter/releases/tag/v1.11.12 with this behaviour fixed.

The same issue with @overwrite btw.

_Originally posted by @rsdsoft in https://github.com/shufo/blade-formatter/issues/313#issuecomment-896274594_

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.12.0. Thanks @rsdsoft!
