### ISSUE TITLE
[Bug] Converting class to lowercase on component attributes

### ISSUE THREAD

**Issue by dianfishekqi** [shufo/blade-formatter#346]
button.blade.php
```
<button
    {{ $attributes->merge([
        'type' => 'submit',
        'class' => 'flex items-center px-4 py-2 rounded-md border cursor-pointer text-white text-sm sm:text-base focus:outline-none transition ease-in duration-300 disabled:opacity-25 ' . ($btnClass ?? 'bg-primary hover:bg-primary-active'),
    ])->except('disabled') }}
    {!! empty($attributes->get('disabled')) ? '' : 'disabled' !!}
>{{ $slot }}</button>
```

blade (before formatting)
```
<x-button btnClass="XXXXXX" />
```

blade (after formatting)
```
<x-button btnclass="XXXXXX" />
```
notice how `btnClass` turns to `btnclass`
also `myBtnClass` turns to `myBtnclass`

this bug was introduced on version  1.12.3

**Comment by dianfishekqi** [comment]
[Line](https://github.com/shufo/blade-formatter/commit/7207014687dc7c22b81e90e9d84c5b563fea860a#diff-cba7cf1e048708aeffd57dc38d0281434f92200218d560d4571ccc17c23e21edR252) causing the problem.

**Comment by shufo** [comment]
Thanks for reporting the issue @dianfishekqi!
Just released fixed version as https://github.com/shufo/blade-formatter/releases/tag/v1.12.4
