### ISSUE TITLE
Bad double braces formating

### ISSUE THREAD

**Issue by Forsakenrox** [shufo/blade-formatter#350]
## Context (Environment)

this began to appear about 1-2 months ago. Previously, the formatting was correct

## Current Behavior
![image](https://user-images.githubusercontent.com/11795286/131470772-690278ba-854d-4d48-b035-4fff185358a5.png)

## Expected Behavior

![image](https://user-images.githubusercontent.com/11795286/131470810-5fe5d687-609d-4893-a511-b5950736c696.png)

I was try to set wrap to 99999, it also doesnt take effect

**Comment by shufo** [comment]
Thanks for reporting the issue @Forsakenrox 

current

```blade
<div class="image">
    {{ asset(
    auth()->user()->getUserMedia('first', 'second'),
) }}
</div>
```

expected

```blade
<div class="image">
    {{ asset(auth()->user()->getUserMedia('first', 'second')) }}
</div>
```

**Comment by shufo** [comment]
@Forsakenrox 
Sorry for late reply. 
Now fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.17.2
