### ISSUE TITLE
Empty class attribute causes incorrect formatting

### ISSUE THREAD

**Issue by claytonrcarter** [shufo/blade-formatter#362]
## Context (Environment)

I'm using v1.12.5 and have run into some unexpected & incorrect formatting caused by an empty `class` attribute.

**All examples are run with** `blade-formatter --wrap-attributes force-expand-multiline --wrap 80 --write <filename>`

This snippet is formatted **correctly**: (Note `<div>` on first line has no `class` attribute)

```php
<div>
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
</div>
```

This snippet is also formatted **correctly**: (Note `<div>` on first line has non-empty `class` attribute)

```php
<div class="foo">
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
</div>
```

This snippet, however, is formatted **incorrectly**: (Note `<div>` on first line has empty `class` attribute)

```php
<div class="">
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
</div>
```

## Current Output

```php
<div
    class="">
    @if (session('status'))
        <div class="
    alert
    alert-success"
>
    {{ session('status') }}
</div>
@endif
</div>

```

## Expected Output

(same as input)
```php
<div class="">
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
</div>
```

## Detailed Description

From my fiddling around, this appears to mostly affect div tags that have empty class attributes and blade directives within the div element. I tried other attributes that are empty and other tags, both of which seemed to format correctly. Removing the `@if` also seemed to result in correct formatting.

## Steps to Reproduce

1. Create a file `foo.blade.php`
2. Copy the "Expected Output" into that file.
3. Run `blade-formatter --wrap-attributes force-expand-multiline --wrap 80 --write foo.blade.php`

Thank you for this excellent project!

**Comment by shufo** [comment]
@claytonrcarter 
Thanks for reporting the issue!

This behaviur is now fixed in https://github.com/shufo/blade-formatter/releases/tag/v1.13.0

https://user-images.githubusercontent.com/1641039/136684729-68498557-01a9-4243-b6a2-ccb4767de077.mp4

**Comment by claytonrcarter** [comment]
And thank you for fixing it!
