### ISSUE TITLE
@php raw block flattened on format when the useTabs option is used

### ISSUE THREAD

**Issue by intelrug** [shufo/blade-formatter#380]
## Context (Environment)
I am trying to format blade file with @php block inside html markup.

File contents:
```blade
<main class="index">
@php
$data = [
[
'href' => '#',
'title' => 'Hi!',
],
];
@endphp
</main>
```

Options:
```js
const options = {
    indentSize: 1,
    useTabs: true,
};
```

## Current Behavior

```blade
<main class="index">
    @php
        $data = [
        [
        'href' => '#',
        'title' => 'Hi!',
        ],
        ];
    @endphp
</main>
```

## Expected Behavior

```blade
<main class="index">
    @php
        $data = [
            [
                'href' => '#',
                'title' => 'Hi!',
            ],
        ];
    @endphp
</main>

```

## Detailed Description

When use this options, formatter working as expected but i don't want to replace all tabs in project with spaces
```js
const options = {
    indentSize: 4,
    useTabs: false,
};
```

## Possible Solution

When I added `useTabs: true` in prettier options [here](https://github.com/shufo/blade-formatter/blob/f75930c2472ec466c2122d482c754c5e385644a8/src/util.js#L46) formatter started working as expected, but I don't think that's a good solution.

**Comment by AlexeiCrr** [comment]
@intelrug , Hi, sorry, what is the possible solution that worked for you in this case? I can't seem to have figured it out.

**Comment by intelrug** [comment]
@AlexeiCrr Without forking the repo - no solution. This is my solution https://github.com/intelrug/blade-formatter/commit/765684eb8fd1834856a965334a04feca09205e7e
