### ISSUE TITLE
Span Tags

### ISSUE THREAD

**Issue by HDVinnie** [shufo/blade-formatter#385]
## Current Behavior

```diff
-<td><span class="label label-success">@lang('user.unlocked')</span></td>
+<td><span
+class="label label-success">@lang('user.unlocked')</span>
+</td>
```

## Expected Behavior

span tags to break properly.

**Comment by shufo** [comment]
Thanks for reporting the issue @HDVinnie.
It might fixed at the latest version. (0.16.1)

https://user-images.githubusercontent.com/1641039/148945767-e0fd4794-f31d-4f92-ad36-599080e0ff14.mp4
