### ISSUE TITLE
Breaking format of output tags {{ }} over multiline

### ISSUE THREAD

**Issue by matthewnessworthy** [shufo/blade-formatter#389]
## Context (Environment)

When formatting multi-line blade output tags, the formatting is changed and indent is lost

## Current Behavior

The formatting of php within blade output tags gets formatted.

## Expected Behavior

The formatting of blade output tags should not be modified (or there should at least be an option to turn off php formatting).

## Detailed Description

existing style:
```
{{ trans(
    'ui.auth.login-or-register.header',
    [
        'companyName' => company_name(),
    ]
) }}

{{ Form::open(
    [
        'route' => ['auth.login.check'],
        'method' => 'post',
        'data-validate-form',
        'data-form-blocking',
    ]
) }}
```

formatted:
```
{{ trans('ui.auth.login-or-register.header', [
    'companyName' => company_name(),
]) }}

{{ Form::open([
    'route' => ['auth.login.check'],
    'method' => 'post',
    'data-validate-form',
    'data-form-blocking',
]) }}
```

## Steps to Reproduce

1.
2.
3.
4.

**Comment by shufo** [comment]
Sorry for late reply.
Since blade-formatter formats PHP code-bases as  PSR-2, so in case of multi-line array arguments, the square brackets in first line will be retained like

```blade
{{ trans('ui.auth.login-or-register.header', [
    'companyName' => company_name(),
]) }}
```

Or you can disable the formatting with the blade comment between `{{-- blade-formatter-disable --}}` and `{{-- blade-formatter-enable --}}`.

```blade
    {{-- blade-formatter-disable --}}
    {{ trans(
        'ui.auth.login-or-register.header',
        [
            'companyName' => company_name(),
        ]
    ) }}
    {{-- blade-formatter-enable --}}
```
