### ISSUE TITLE
Option to put closing HTML tag on new line

### ISSUE THREAD

**Issue by mattgreenfield** [shufo/blade-formatter#394]
## Context (Environment)

Some members of my team use different tools to format their blade files and I would like mine to match to reduce git diffs.
I would like the closing `>` to be on a new line when wrapping attributes.

## Current Behavior

I am able to change the `wrap attributes` setting to get the following format:
```html
<div class="item"
        role="menu"
        aria-labelledby="user-menu-button"
        tabindex="-1"
        x-transition:enter="transition ease-out duration-100"
        x-show="open"
        @click.outside="open ? open = !open : false">
```

## Expected Behavior

I would like the closing `>` to be on a new line:
```html
<div class="item"
        role="menu"
        aria-labelledby="user-menu-button"
        tabindex="-1"
        x-transition:enter="transition ease-out duration-100"
        x-show="open"
        @click.outside="open ? open = !open : false"
>
```

## Detailed Description

I believe this could be achieved with a new option(s) for the `wrap attributes` setting.

For what it's worth, this is the [default behaviour of Prettier ](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AJPoC8AOuABZyUDOcpu6AhjAwLRWYBecJIATnAwA2ggJ4sARpgDmbCC0wwWAd14MADlTphBDKlR4VeEXJJmHjDKBBiGW23ZpAA+CsIioA9FmxOQAGhAINRhMaCpkUAZeIyUABSiEcJQGbAgCfxBxVTAAazgYAGUGAFs4ABlMKDhkADMhGgCshlz8grVmyqlkGF4AVzgAuGLxOHR0UbLLKV6GKTgAMQheYqYQqC7k3pgIDLIYYsEAdTIFOCp2sDgCxIUcBRFkcD0MyppeGFjVKRXa+oGQABWVAAHgVOoI4ABFXrWapIOqCBogdq8N6PcQMEaCDJqXiVGCHAg2ZAADgADAFcRAaIdVGpHriznBeNhqgEAI4w+CfIJJEC6FhVUajDL8TmYfifWY-eF-AI0YqYbp9f7sdYQ6Gw36I-7McSE9DEpAAJgCPQYmEEnQAwhBijKQFYqhlejQACqYpIIpHYfoASSg41gBTAeOCAEFAwUYCIIdqkUDgQAhbJ5QolcqVOHeuAAX1zQA)

**Comment by shufo** [comment]
@mattgreenfield 
Please try `wrap attributes` setting to `force-expand-multiline`.

It will format below template

```blade
<div class="item"
        role="menu"
        aria-labelledby="user-menu-button"
        tabindex="-1"
        x-transition:enter="transition ease-out duration-100"
        x-show="open"
        @click.outside="open ? open = !open : false">
```

into 

```blade
<div
    class="item"
    role="menu"
    aria-labelledby="user-menu-button"
    tabindex="-1"
    x-transition:enter="transition ease-out duration-100"
    x-show="open"
    @click.outside="open ? open = !open : false"
>
```

**Comment by mattgreenfield** [comment]
Thanks @shufo - this does indeed format it as per the prettier link I included. 

The problem does seem to be resolved - I think my teammates changed their settings but they somehow had a mix of the two:
```
<div class="item"
     role="menu"
     aria-labelledby="user-menu-button"
     tabindex="-1"
     x-transition:enter="transition ease-out duration-100"
     x-show="open"
     @click.outside="open ? open = !open : false"
>
```

I'll re-open this if it comes up again and will investigate what this above format is called in their editor.

Thanks again
