### ISSUE TITLE
Ability for disable formatting for certain lines of code

### ISSUE THREAD

**Issue by mattgreenfield** [shufo/blade-formatter#395]
## Context (Environment)

I am running blade-formatter on all blade files on a before push git hook. There are some parts of some files that this breaks/
While I could add this file to the `.bladeignore` file, I still want the rest of the file to be formatted.

## Current Behavior

There is no way to disable blade formatter for a section of the file, only the whole file.

## Expected Behavior

I should be able to disable formatting with HTML or Blade comments. This would work in the same way that ES Lint and Prettier do:
- disable the whole file with a comment
- disable the next line with a comment
- disable until there is an enable comment
https://eslint.org/docs/user-guide/configuring/rules#disabling-rules

**Comment by shufo** [comment]
Thanks for suggesting feature @mattgreenfield.

Just released https://github.com/shufo/blade-formatter/releases/tag/v1.16.0 with ignore statement feature. 
Please see usage https://github.com/shufo/blade-formatter#disabling-format-in-file.

**Comment by mattgreenfield** [comment]
Thank you!
