### ISSUE TITLE
Ignore Code Within <script> Tag

### ISSUE THREAD

**Issue by HDVinnie** [shufo/blade-formatter#4]
Ignore code within tags like `<script nonce="{{ Bepsvpt\SecureHeaders\SecureHeaders::nonce() }}">`

**Comment by shufo** [comment]
@HDVinnie 
Thanks for feedback! I'll try figure out the problem. Also #1 #2 #3

**Comment by HDVinnie** [comment]
@shufo Thank you. Really looking forward to using this on some older projects once some of the issues are resolved. Great idea behind this package. Well Done!
