### ISSUE TITLE
blade tag for ignore itself will be formatted

### ISSUE THREAD

**Issue by yaegassy** [shufo/blade-formatter#441]
## Detailed Description

It's not a fatal bug, but I'm curious, so I'm reporting an issue.

This is about the new feature added in `v1.16.0` to disable formatting by blade comments.

`{{-- blade-formatter-disable-next-line --}}` etc, blade comment itself will be formatted. Is this a specification?

## DEMO (mp4)

- <https://github.com/yaegassy/coc-blade/pull/2>

## Current Behavior

**Command**:

`cat sample.blade.php | blade-formatter --stdin`

**Before**:

```blade
@section('content')
    <section id="content">
        <div class="container mod-users-pd-h">
            <div class="pf-user-header">
                      {{-- blade-formatter-disable-next-line --}}
                      <p>@lang('users.index')</p>
            </div>
        </div>
    </section>
@endsection
```

**After**:

```blade
@section('content')
    <section id="content">
        <div class="container mod-users-pd-h">
            <div class="pf-user-header">
                {{-- blade-formatter-disable-next-line --}}
                      <p>@lang('users.index')</p>
            </div>
        </div>
    </section>
@endsection
```

## Expected Behavior

```blade
@section('content')
    <section id="content">
        <div class="container mod-users-pd-h">
            <div class="pf-user-header">
                      {{-- blade-formatter-disable-next-line --}}
                      <p>@lang('users.index')</p>
            </div>
        </div>
    </section>
@endsection
```

**Comment by shufo** [comment]
@yaegassy 
Thanks for reporting the issue! 
I also worried about how to deal with this problem while implementing this feature.
Then I've thought it would be easy to read if the blade comments are indented as normal blade comments. If comments itself are keep its position, it's unlikely readable IMHO.

Also, from an implementation view, it was a bit complicated to keep indentation position than formatting comments.

So it is currently intended behaviour.

BTW big thanks for merge this feature to coc-blade!

**Comment by yaegassy** [comment]
@shufo Thanks for the reply! If it is a spec, no problem. I will close this issue. 🙇
