### ISSUE TITLE
Add project wide configuration like .prettierrc

### ISSUE THREAD

**Issue by mogottsch** [shufo/blade-formatter#450]
## Context (Environment)

We are trying to use blade-formatter in our project and we all need the same options. In order to accomplish this, we currently share our options in a markdown file. Each time something changes everyone has to adapt to these changes, e.g. by updating their vscode config.

## Current Behavior

We have to manually update our options each time the project-wide options change.

## Expected Behavior

Automatically adapt to a project-wide configuration.

## Possible Solution

Add a `.blade-formatterrc` or `"blade-formatter"` key-value pair in the `package.json`, that is read and used as options (if it exists).

**Comment by shufo** [comment]
@mogottsch 
Just released blade-formatter https://github.com/shufo/blade-formatter/releases/tag/v1.17.0 with runtime configuration support.
please see [docs](https://github.com/shufo/blade-formatter#configuring-blade-formatter)

Runtime configuration supported VSCode Extension is released at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.11.0
