### ISSUE TITLE
Inserting padding in blank lines

### ISSUE THREAD

**Issue by eduardoarandah** [shufo/blade-formatter#48]
## Expected Behavior
Don't pad blank lines

## Current Behavior
Pads new lines

## Possible Solution
Delete all content in blank lines

## Steps to Reproduce

- Create a file with blank lines
- blade-formatter --write --indent-size=8
- Check padding in blank lines

## Context (Environment)

Checked in VIM (where it doesn't trim blank lines by default)

## Detailed Description

Check screenshot

![image](https://user-images.githubusercontent.com/4065733/78201125-0a760800-744e-11ea-90d7-981d939e5515.png)

This command messes up with `vap` in vim which "selects around paragraph"
![image](https://user-images.githubusercontent.com/4065733/78201153-24afe600-744e-11ea-891d-4e62f5951d98.png)

## Possible Implementation

Trim blank lines

**Comment by shufo** [comment]
published [v1.1.5](https://www.npmjs.com/package/blade-formatter/v/1.1.5) with this fix
