### ISSUE TITLE
[improve] handle switch, case and break directive auto line breaking

### ISSUE THREAD

**Issue by shufo** [shufo/blade-formatter#483]
This is an improvement indeed. It would be nice if also these cases could be handled:

    @switch($type) @case(1) $a = 3; @break @case(2) @case(3) $a = 4; @break @default $a = null; @endswitch

and 

    @can('can') $a = 1; @endcan @if (true) $a = 1; @else $a = 2; @endif

They currently result in 

    @switch($type)
        @case(1) $a = 3; @break @case(2)
            @case(3) $a = 4; @break @default $a = null;
        @endswitch

and

    @can('can')
        $a = 1;
        @endcan @if (true)
        $a = 1; @else $a = 2;
        @endif

_Originally posted by @Polfo in https://github.com/shufo/blade-formatter/issues/474#issuecomment-1044535709_

**Comment by Polfo** [comment]
It improved, thanks. But unfortunately, there still are issues like with this expample:

    @switch($type)
        @case(1)
            $a = 3;
        @break

        @case(2)
        @case(3)
            $a = 4;
        @break

    @case(3)
        $a = 4;
    @break

    @default
        $a = null;
    @endswitch

**Comment by shufo** [comment]
@Polfo 
Thanks for the example! I'll look into that case.
