### ISSUE TITLE
Oneline PHP statements are broken

### ISSUE THREAD

**Issue by Wulfheart** [shufo/blade-formatter#493]
## Context (Environment)

As per [this article](https://gummibeer.dev/blog/2020/phpdoc-in-blade-views/) I am trying to integrate raw php tags with comments for typehinting. Something like this provides autocompletion:
```blade
<?php /** @var \App\Models\Game $game */ ?>
@foreach ($preview['new'] as $game)
   <x-game.preview.new :game="$game" />
@endforeach
```

## Current Behavior
``` php
<?php /** @var \App\Models\Game $game */ ?>
```
becomes
``` php
<?php /** @var \App\Models\Game $game */ 
?>
```
## Expected Behavior

``` php
<?php /** @var \App\Models\Game $game */ ?>
```
becomes
``` php
<?php /** @var \App\Models\Game $game */ ?>
```

## Possible Solution

Don't add a linebreak if there is only a comment wrapped in the php tag.

**Comment by shufo** [comment]
HI @Wulfheart. 
Thanks for reporting the issue!
I hadn't thought of that use case, so I'll look into it.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.19.0
prettier-blade-plugin: https://github.com/shufo/prettier-plugin-blade/releases/tag/v1.0.11

**Comment by Wulfheart** [comment]
Thanks!
You rock!
