### ISSUE TITLE
indentation stripped on an array of additional data passed to @include

### ISSUE THREAD

**Issue by thedavidthomas** [shufo/blade-formatter#501]
## Context (Environment)

I'm using the Laravel Blade formatter v0.13.0 plugin in Visual Studio Code on a Mac

## Current Behavior

Indenting arrays passed inline to an `@include` is stripped

## Expected Behavior

I would expect the formatter to not strip the indenting of the passed array similar to if it was a php array
```
@php
$array = [
    'buttons' => [
        [
            'style' => 'link',
            'link' => [
                'title' => 'Call to Action',
                'url' => '#',
                'target' => '_self',
            ],
        ],
    ],
];
@endphp
```

## Steps to Reproduce

1. Format the following code 
```
@include('parts.partials.buttons.btn-group', ["buttons" => [
    [
        "style" => "link",
        "link" => [
            "title" => "Call to Action",
            "url" => "#",
            "target" => "_self",
        ],
    ],
]])
```

2. Observe that the output is the following.
```
@include('parts.partials.buttons.btn-group', ["buttons" => [
[
"style" => "link",
"link" => [
"title" => "Call to Action",
"url" => "#",
"target" => "_self",
],
],
]])
``

**Comment by shufo** [comment]
Hi @thedavidthomas 
Thanks for reporting the issue.

This behaviour is fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.20.2

**Comment by shufo** [comment]
VSCode: https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.13.1
