### ISSUE TITLE
Inilne script tag removes previous DOM

### ISSUE THREAD

**Issue by ernix** [shufo/blade-formatter#508]
## Context (Environment)

```
% blade-formatter --version
1.20.4
```

## Current Behavior

Format following html:

```blade
<p>foo</p><p>bar</p><script>document.write("buz");</script><p>blah</p>
```

it turns out:

```blade
<p>foo</p>
<script>
    document.write("buz");
</script><p>blah</p>
```

Somehow `<p>bar</p>` was removed.

## Expected Behavior

```
<p>foo</p>
<p>bar</p><script>
    document.write("buz");
</script><p>blah</p>
```

**Comment by shufo** [comment]
Hi @ernix
Thanks for creating the issue!
I'll take a look into it.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.20.5

**Comment by ernix** [comment]
@shufo Thanks, confirmed.

This might be wrong place to ask, but can I control the way to format whitespaces/newlines like `--whitespace-sensitivity` in prettier HTML plugin?
https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting

Both of `span` and `script` are inline block elements, thus a newline between `</span>` and `<script>` produce a whitespace that formatter tools should not change.

```html
<span>foo</span><span>hoge</span><script>document.write("buz");</script>bar
<!-- foobarbuz -->
```

```html
<span>foo</span><span>bar</span>
<script>
    document.write("buz");
</script>
<!-- foobar buz -->
```

**Comment by shufo** [comment]
@ernix
I see. This is certainly an issue to resolve. 
I've created https://github.com/shufo/blade-formatter/issues/511 as a separated issue, so let's proceed there
