### ISSUE TITLE
line wrap on @set directive breaks the page

### ISSUE THREAD

**Issue by formikaio** [shufo/blade-formatter#542]
## Current Behavior

For this sample line: 

`@set $myVariableWithVeryVeryVeryVeryVeryLongName = ($myFirstCondition || $mySecondCondition) ? 'My text' : 'My alternative text'`

the formatter adds a line wrap (result is 2 lines):

```
@set $myVariableWithVeryVeryVeryVeryVeryLongName = ($myFirstCondition || $mySecondCondition) ? 'My text' : 'My
alternative text'
```

so the page breaks.

## Expected Behavior

The formatter should let the line as it is.

## Possible Solution

The formatter should not apply line wrap on @set directive.

P.s. Also referenced [here](https://github.com/shufo/vscode-blade-formatter/issues/213)

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.23.4

**Comment by shufo** [comment]
Note: To prevent line wrap on long line, please put `@set` expression in parentheses.

e.g. 

```blade
@set($myVariableWithVeryVeryVeryVeryVeryLongName = ($myFirstCondition || $mySecondCondition) ? 'My text' : 'My alternative text')

```

**Comment by formikaio** [comment]
Thanks a lot @shufo!

**Comment by formikaio** [comment]
The last release v0.20.30 breaks it again, even using parentheses. 
@shufo can you please look into it?
