### ISSUE TITLE
Unexpected behavior with string ending with dollar sign ($) inside nested script

### ISSUE THREAD

**Issue by jhoff** [shufo/blade-formatter#565]
## Context (Environment)

When an inline script that is nested inside of a blade directive contains a string that ends with a dollar sign ($), the parser replaces the text unexpectedly

## Current Behavior

Given this input:

```
@section('foo')
    <script>
        alert('$');
    </script>
@endsection
```

The formatter returns this output:

```
@section('foo')
    <script>
        alert('@endsection);
    </script>
@endsection
```

## Expected Behavior

It shouldn't do that :)

## Detailed Description

This issue initially manifested itself in my code as a `directive in scripts parsing error` error, which wasn't too helpful.

I then built the package from source and threw the original error which was `Unbalanced right delimiter found in string at position 1911` thrown by XRegExp.matchRecursive

I was then able to reduce the issue down to the example above, which I think is the root cause.

## Possible Solution

I'm not sure how to solve it, as theres a lot of regex voodoo going on. I'm guessing the problem lies somewhere in there but it's a bit over my head without diving in. Hoping someone else more familiar might know.

## Steps to Reproduce

Create file with input provided above and run formatter against it.

**Comment by shufo** [comment]
@jhoff 
Thanks for detailed information! It helped a lot.

Fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.23.7

**Comment by jhoff** [comment]
Fantastic! Thanks for fixing it so quickly!
