### ISSUE TITLE
More unexpected behavior with string ending with dollar sign ($) inside nested script

### ISSUE THREAD

**Issue by jhoff** [shufo/blade-formatter#569]
## Context (Environment)

The plot thickens! ( Followup to #565 )

While the previously reported bug did exist and the recent fix resolved that simple example, it seems the problem goes deeper. If that same example contains another pair of conditional directives, the problem persists.

Additionally, if that same conditional directive is inside of the script tag, then we get a `directive in scripts parsing error`.

## Current Behavior

Given this input

```
@section('foo')
    <script>
        alert('anything as long as the string ends with a dollar sign -> $');
    </script>
    @if(true)
        //
    @endif
@endsection
```

The formatter returns this:

```
@section('foo')
    <script>
        alert('anything as long as the string ends with a dollar sign -> @endsection');
    </script>
    @if(true)
        //
    @endif
@endsection
```

Additionally, if we move the `if / endif` inside of the script tag

```
@section('foo')
    <script>
        alert('anything as long as the string ends with a dollar sign -> $');

        @if(true)
            //
        @endif
    </script>
@endsection
```

It results in an error caught [here](https://github.com/shufo/blade-formatter/blob/master/src/formatter.ts#L351) which is `Unbalanced right delimiter found in string at position 74` from `XRegExp.matchRecursive`

Hopefully this still helps!

**Comment by jhoff** [comment]
Oooooh interesting.

It seems the problem is isolated to when the `$` immediately follows a single quote `'`

If I use a double quote instead, all of the issues go away...

```
@section('foo')
    <script>
        alert("for some reason this works $");
    </script>
    @if (true)
        //
    @endif
@endsection
```

```
@section('foo')
    <script>
        alert("so does this $");

        @if(true)
            //
        @endif
    </script>
@endsection
```

**Comment by jhoff** [comment]
Thanks @shufo!

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.23.8

Thanks for detailed ticket @jhoff!
