### ISSUE TITLE
Aliased component formatted incorrectly when starting with @break

### ISSUE THREAD

**Issue by jhoff** [shufo/blade-formatter#570]
## Context (Environment)

I'm sure this is a hyper-specific issue, but thought it might be worth bringing up.

We have an aliased component called `@breakdown` that is being parsed incorrectly because it starts with `@break`

## Current Behavior

Given the following code:

```
                @breakdown(['breakdown' => $cart_breakdown, 'existing_customer' => false])
                @endbreakdown
```

The parser splits the directive after seeing `@break`

```
                @break

                down(['breakdown' => $cart_breakdown, 'existing_customer' => false])
                @endbreakdown
```

## Detailed Description

This is probably related to #554 but can be easily avoided for the time being by either renaming the component or adding a `blade-formatter-disable` comment

## Possible Solution

Ensure that matched `phpKeywordEndTokens` aren't immediately followed by another letter

**Comment by shufo** [comment]
Thank you @jhoff.
Fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.25.0
