### ISSUE TITLE
content insde @aware are not indented

### ISSUE THREAD

**Issue by Rizky92** [shufo/blade-formatter#576]
## Context (Environment)
Laravel 8 introduced [`@aware` directive](https://laravel.com/docs/9.x/blade#accessing-parent-data) for blade component to access variables from parent component. When trying to use it, the content inside `@aware` aren't indented as opposed to `@props` which has similar format.

## Current Behavior
The content inside `@aware` aren't indented as opposed to `@props` which has similar format.

## Expected Behavior
The content inside `@aware` supposed to be indented just like `@props`.

## Steps to Reproduce
1. Create a blade component.
2. Add `@props` and `@aware` and pass some data.
3. Run blade-formatter. Notice `@aware` does not have indentation as opposed to `@props`.

**Comment by shufo** [comment]
Thanks @Rizky92 for creating the issue.
Fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.24.0
