### ISSUE TITLE
Break all properties or none

### ISSUE THREAD

**Issue by mblarsen** [shufo/blade-formatter#64]
## Expected Behavior

```
.............................|<--- 120 chars here
<div this="xxx" has="" many="" props="" one="more">

or

<div 
    this="xxx" 
    has="" 
    many="" props=""
    one="more"
>
```

## Current Behavior

```
<div this="xxx" has="" many="" 
     props="" one="more">
```
When the lines reaches max (default 120) it breaks a tag into multiple lines. It seems like it tries to fill up a line at a time or something.

## Possible Solution

If max width is reach break a tags props one per line. 

## Steps to Reproduce

Make a long line.

**Comment by slovenianGooner** [comment]
Think this PR fixes this. 

https://github.com/shufo/blade-formatter/pull/151
