### ISSUE TITLE
Mix of open/closed HTML tag and directives

### ISSUE THREAD

**Issue by shufo** [shufo/blade-formatter#646]
## Context (Environment)

- v1.26.10

## Current Behavior

Currently the mix of open/closed HTML tag and directives result in unexpected format.

```blade
@if ($user)
  <div>
@else
  </div>
@endif
```

will format into

```blade
@if ($user)
    <div>
    @else
    </div>
@endif

```

## Expected Behavior

It should be indent html tags based on blade directive

### Input

```blade
@if ($user)
  <div>
@else
  </div>
@endif
```

### Output

```blade
@if ($user)
  <div>
@else
  </div>
@endif
```

## Detailed Description

It should set the indentation base to be inside of the directive, but not outside of the directive.

```blade
<div>
  @if ($user)
    <div>
  @else
    </div>
  @endif
</div>
```

## Work around

Since the syntax preference between HTML and Blade is basically unresolvable, you should try to keep the HTML Open/Close tags as complete as possible within a single logical directive block

e.g. 

```blade
<div>
  @if ($user)
    <div></div>
  @else
    <p></p>
  @endif
</div>
```

**Comment by francoism90** [comment]
@shufo Any update on this? Because this seems to happen with just Prettier as formatter.

**Comment by shufo** [comment]
@francoism90 
Sorry, still in progress due to the many edge cases.

**Comment by montchr** [comment]
Still an issue afaik, should not have been closed by the bot.
