### ISSUE TITLE
formatter will perpetually add tab intent every time formatter runs

### ISSUE THREAD

**Issue by dgibbs64** [shufo/blade-formatter#666]
## Context (Environment)
VSCode and prettier cli

## Current Behaviour

When a blade file has a `<script>` tag and is in a `@section` any code in that tag will be given a new tab intent every single time. This causes the code to slowly "drift" away.
Run once
![image](https://user-images.githubusercontent.com/4478206/180759187-9cf88b2f-2a24-4595-ad5b-657608888899.png)
Run twice
![image](https://user-images.githubusercontent.com/4478206/180759241-85fc83e6-67c2-4fb9-a86f-60cd7f44790d.png)
Run three times
![image](https://user-images.githubusercontent.com/4478206/180759294-3db44e4d-11ae-4b44-8675-ed04bee5b388.png)
This means everytime I want to format these files I have to manually go back and un intent them.
## Expected Behaviour

The formatter should not perpetually indent every time it runs.
## Steps to Reproduce

The below example code should allow you to replicate the issue.
```
@section('section')
    <script type="text/template" id="test">
        <div>
            Test          
        </div>
    </script>
@endsection
```

**Comment by shufo** [comment]
Thanks @dgibbs64 

blade-formatter is currently interpreting body of script tag as JS, so that could be the cause. 
I'll look into it.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.26.15

**Comment by dgibbs64** [comment]
Thats awesome. Thank you so much ♥️♥️
