### ISSUE TITLE
Prevent multi-line Comments collapsing into a single line. 

### ISSUE THREAD

**Issue by thedavidthomas** [shufo/blade-formatter#703]
We are using Blade with WordPress, in WordPress a comment is used at the top of the file to name the template and this name is shown in a select list in the admin to choose a template.

Using the VS Code Extention

The following code
```
{{-- 
  Template Name: Custom Template
--}}
@extends('frontend.layouts.app')

@section('content')
...
@endsection
```

when formatted is collapsing the comment into a single line
```
{{-- Template Name: Custom Template --}}
@extends('frontend.layouts.app')

@section('content')
    ...
@endsection
```

this then shows in the template select box to the admin as: `Custom Template --}}` instead of the expected `Custom Template`

I'd rather not use PHP and Blade comments together but to get around this I am currently using:
{{-- /*
    Template Name: Custom Template
*/ --}}

Is there a way for the formatter to not collapse blade comments into a single line?

**Comment by shufo** [comment]
Currently there is no option to stop comment collapses though, you can use ignore statement to temporarily disable formatting.

```blade
{{--blade-formatter-disable-next-line--}}
{{--
Template Name: Custom Template
--}}

```

or 

```blade
{{--blade-formatter-disable--}}
{{--
Template Name: Custom Template
--}}
{{--blade-formatter-enable--}}
```

But I think all line breaks and spaces in comments should be preserved, so I'll look into why this is happening.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.29.6
