### ISSUE TITLE
[Feature Request] allows a custom attribute sort regex

### ISSUE THREAD

**Issue by ryanmortier** [shufo/blade-formatter#708]
Hi,

I see that the https://github.com/shufo/html-attribute-sorter package allows a custom attribute sort regex. I'm wondering if you can support that functionality in this package?

Thanks.

**Comment by shufo** [comment]
Hi @ryanmortier 
That feature will be implemented in soon. Please wait a little.

**Comment by shufo** [comment]
Added custom attribute sort regex at https://github.com/shufo/blade-formatter/releases/tag/v1.31.0
