### ISSUE TITLE
script type "text/template" or "application/json" and blade directive causes error

### ISSUE THREAD

**Issue by Grldk** [shufo/blade-formatter#723]
Using version 1.29.7 I'm trying to format blade files in one of our projects, but end up running into quite a few errors. These errors seem to be caused by our use of `<script type="text/template">` or `<script type="application/json">` in combination with blade directives. 

Simplified way to reproduce:

### This works:

Before:
```
<script>
@if(true)
<div class="true"></div>
@else
var test = 'false';
@endif
</script>
```

After:
```
<script>
    @if (true)
        var test = 'true';
    @else
        var test = 'false';
    @endif
</script>
```

### This doesn't:
```
<script type="text/template">
@if(true)
<div class="true"></div>
@else
<div class="false"></div>
@endif
</script>
```
Returns: `message: "Can't format blade: something goes wrong.\n" +
    'Please check if template is too complicated or not. Or simplify template might solves issue.',`

### Expected:
```
<script type="text/template">
    @if (true)
        <div class="true"></div>
    @else
        <div class="false"></div>
    @endif
</script>
```

`<script type="application/json">` with blade directive throws the same error.

**Comment by shufo** [comment]
Thanks for reporting the issue @Grldk 
It seems related to https://github.com/shufo/blade-formatter/issues/666

I fixed to treat `text/template` type script as plain html in that issue, so that's why your template throws an error. `application/json` is just not supported yet.

Maybe we should rethink how to treat script types.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.29.8
