### ISSUE TITLE
[Feature Request] Format classes in the @class directive

### ISSUE THREAD

**Issue by alexmandrikdev** [shufo/blade-formatter#732]
Could you please make the class sorting work with the @class directive?

```
@class([
    'p-4',
    'font-bold' => $isActive,
    'text-gray-500' => !$isActive,
    'bg-red' => $hasError,
])
```

**Comment by shufo** [comment]
@alexmandrikdev 
Thanks for suggesting the feature. I think it's not bad idea but might be out of scope of this project. 
From point of view of directive, it's clearly blade. On the other hand, from point of view of php, it's php format problem. 
So it's ambiguous.

As a policy for this project, I want to stay away from php formatting issues as possible, so I'll have to give some thought to whether this feature is really necessary.
