### ISSUE TITLE
[Formatting Bug]: @error directive forces newline

### ISSUE THREAD

**Issue by jerothor** [shufo/blade-formatter#791]
### Version

1.32.7

### Template before formatting

```blade
@error('password') <div class="invalid-feedback">{{ $message }}</div> @enderror
```

### Template after formatting

```blade
@error('password')
    <div class="invalid-feedback">{{ $message }}</div>
@enderror
```

### Expected Behaviour

the error directive should not force newlines

it should work just like the `@if` directive, where i can have it all on a single line if i want

**Comment by shufo** [comment]
This behaviour is currently intended.
Maybe we should have an option to disable inlined directives to be not formatted at all.
