### ISSUE TITLE
[Bug]: `message: "Cannot find module 'tailwindcss/defaultTheme'"`

### ISSUE THREAD

**Issue by bilogic** [shufo/blade-formatter#814]
### Description

I installed blade-formatter globally to `/usr/bin`, using `npm set prefix /usr`, i.e.
```
npm set prefix /usr
npm install -g blade-formatter

# which blade-formatter
/usr/bin/blade-formatter
```

Each time I run it with `--sort-tailwindcss-classes`, I get there error `message: "Cannot find module 'tailwindcss/defaultTheme'"`

Without `--sort-tailwindcss-classes`, `blade-formatter` formats correctly.

### Expected Behavior

`blade-formatter` should format without error

### Actual Behavior

`blade-formatter` throws `message: "Cannot find module 'tailwindcss/defaultTheme'"`

**Comment by bilogic** [comment]
More info provided in the OP update. Thank you.

**Comment by shufo** [comment]
Thanks for creating the issue @bilogic 
I could not reproduce in my environment but it might be there have not tailwindcss module in global.

**Comment by shufo** [comment]
Global installation is a little complicated to resolve dependencies, so I would recommend using local dependencies if possible.

```bash
$ cd your_project
$ npm install --save-dev blade-formatter tailwindcss
$ ./node_modules/.bin/blade-formatter --sort-tailwindcss-classes target.blade.php
```

**Comment by bilogic** [comment]
Hey thanks! I managed to resolve the issue already, can't remember how though. Haha
