### ISSUE TITLE
[Feature]: How is tailwind sorted?

### ISSUE THREAD

**Issue by bilogic** [shufo/blade-formatter#846]
### Description

https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted

Like to ask if the sorting logic is based on the link above

### Suggested Solution

If not, possible to sort based on the official recommendation?

**Comment by shufo** [comment]
Yes, It's same as [tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted)

**Comment by bilogic** [comment]
Thank you!
