### ISSUE TITLE
[Formatting Bug]: Livewire parameters broken after format

### ISSUE THREAD

**Issue by donnyxray** [shufo/blade-formatter#944]
### Version

1.41.0

### Template before formatting

```blade
<flux:table :paginate="$this->accounts">
...
</flux:table>
```

### Template after formatting

```blade
<flux:table :paginate="$this - > accounts">
...
</flux:table>
```

### Expected Behaviour

The arrow should be left as is, not broken into pieces.

**Comment by tvarwig** [comment]
Having Same issue

**Comment by RayGuo-ergou** [comment]
I have created a PR for it: https://github.com/shufo/blade-formatter/pull/943

**Comment by haniramadhan-kkp** [comment]
I'm experiencing the same issue when using Flux. Hopefully, this can be resolved soon.
Thank you!

**Comment by ferremek** [comment]
Also experiencing this issue! Anyone know how I can use this Blade Formatter without breaking the Livewire components?

**Comment by tvarwig** [comment]
> #943

There is a open PR that @RayGuo-ergou did but the maintainer @shufo hasn't looked into it yet. I might fork it with the PR. It has been over a month.
